### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by Seasawher** [arthurpaulino/chrome-lean-unicode#5]
When I manually add a URL pattern, this extension does not work well on that site.

**Comment by arthurpaulino** [comment]
Which site are you trying to add? Indeed, there should be some limitations due to my limited frontend knowledge.

**Comment by Seasawher** [comment]
I want to add `https://github.com/`

**Comment by arthurpaulino** [comment]
What if you delete that last slash `/`?
If it works, it looks like a small fix/improvement worth PR'ing

**Comment by Seasawher** [comment]
I tried removing the last slash, but it still doesn't work

**Comment by arthurpaulino** [comment]
I see. I'm sorry but I don't have enough time to debug it now. Feel free to try and open a PR if you figure it out.

**Comment by Seasawher** [comment]
I tested this again.

Immediately after installation, it was not possible to use this at the added URL, but after a short wait, for example by reloading the window, it became usable.

The problem seems to be that it cannot be used immediately after installation.
